module OpenHRP
{
  typedef sequence<double> dSequence;
  
  interface creekSequencePlayerService
  {
    void waitInterpolation();
    
    boolean setJointAngles(in dSequence jvs, in double tm);
    boolean setJointAngle(in string jname, in double jv, in double tm);
    
    boolean setBasePos(in dSequence pos, in double tm);
    boolean setBaseRpy(in dSequence rpy, in double tm);
    boolean setZmp(in dSequence zmp, in double tm);
    
    boolean isEmpty();

    boolean setBasePosRel(in dSequence pos, in double tm);

    void jointCalib(in long scale);
    
    //void loadPattern(in string basename, in double tm);
    
    //void clear();
    //void clearNoWait();
  };
};
