// -*- mode: idl; indent-tabs-mode: t; tab-width: 4; c-basic-offset: 4; -*-

module OpenHRP {
	interface creekArmControlCartesianService
	{
		void setArm(in long armId);  // 0:rarm, 1:larm, 2:none
		
		void setVelocity(in double vtrans, in double vomega, in double velbow);
		void setTranslationVelocity(in double vtrans);
		void setAngularVelocity(in double vomega);
		void setElbowVelocity(in double velbow);
	};
};
