// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "creekArmControlCartesianService.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



OpenHRP::creekArmControlCartesianService_ptr OpenHRP::creekArmControlCartesianService_Helper::_nil() {
  return ::OpenHRP::creekArmControlCartesianService::_nil();
}

::CORBA::Boolean OpenHRP::creekArmControlCartesianService_Helper::is_nil(::OpenHRP::creekArmControlCartesianService_ptr p) {
  return ::CORBA::is_nil(p);

}

void OpenHRP::creekArmControlCartesianService_Helper::release(::OpenHRP::creekArmControlCartesianService_ptr p) {
  ::CORBA::release(p);
}

void OpenHRP::creekArmControlCartesianService_Helper::marshalObjRef(::OpenHRP::creekArmControlCartesianService_ptr obj, cdrStream& s) {
  ::OpenHRP::creekArmControlCartesianService::_marshalObjRef(obj, s);
}

OpenHRP::creekArmControlCartesianService_ptr OpenHRP::creekArmControlCartesianService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::OpenHRP::creekArmControlCartesianService::_unmarshalObjRef(s);
}

void OpenHRP::creekArmControlCartesianService_Helper::duplicate(::OpenHRP::creekArmControlCartesianService_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

OpenHRP::creekArmControlCartesianService_ptr
OpenHRP::creekArmControlCartesianService::_duplicate(::OpenHRP::creekArmControlCartesianService_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

OpenHRP::creekArmControlCartesianService_ptr
OpenHRP::creekArmControlCartesianService::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


OpenHRP::creekArmControlCartesianService_ptr
OpenHRP::creekArmControlCartesianService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

OpenHRP::creekArmControlCartesianService_ptr
OpenHRP::creekArmControlCartesianService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_creekArmControlCartesianService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_creekArmControlCartesianService* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_creekArmControlCartesianService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* OpenHRP::creekArmControlCartesianService::_PD_repoId = "IDL:OpenHRP/creekArmControlCartesianService:1.0";


OpenHRP::_objref_creekArmControlCartesianService::~_objref_creekArmControlCartesianService() {
  
}


OpenHRP::_objref_creekArmControlCartesianService::_objref_creekArmControlCartesianService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::OpenHRP::creekArmControlCartesianService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
OpenHRP::_objref_creekArmControlCartesianService::_ptrToObjRef(const char* id)
{
  if( id == ::OpenHRP::creekArmControlCartesianService::_PD_repoId )
    return (::OpenHRP::creekArmControlCartesianService_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::OpenHRP::creekArmControlCartesianService::_PD_repoId) )
    return (::OpenHRP::creekArmControlCartesianService_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_clong
class _0RL_cd_c027abffb118df27_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_c027abffb118df27_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
};

void _0RL_cd_c027abffb118df27_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_c027abffb118df27_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;

}

const char* const _0RL_cd_c027abffb118df27_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_c027abffb118df27_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_c027abffb118df27_00000000* tcd = (_0RL_cd_c027abffb118df27_00000000*)cd;
  OpenHRP::_impl_creekArmControlCartesianService* impl = (OpenHRP::_impl_creekArmControlCartesianService*) svnt->_ptrToInterface(OpenHRP::creekArmControlCartesianService::_PD_repoId);
  impl->setArm(tcd->arg_0);


}

void OpenHRP::_objref_creekArmControlCartesianService::setArm(::CORBA::Long armId)
{
  _0RL_cd_c027abffb118df27_00000000 _call_desc(_0RL_lcfn_c027abffb118df27_10000000, "setArm", 7);
  _call_desc.arg_0 = armId;

  _invoke(_call_desc);



}
OpenHRP::_pof_creekArmControlCartesianService::~_pof_creekArmControlCartesianService() {}


omniObjRef*
OpenHRP::_pof_creekArmControlCartesianService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::OpenHRP::_objref_creekArmControlCartesianService(ior, id);
}


::CORBA::Boolean
OpenHRP::_pof_creekArmControlCartesianService::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::OpenHRP::creekArmControlCartesianService::_PD_repoId) )
    return 1;
  
  return 0;
}

const OpenHRP::_pof_creekArmControlCartesianService _the_pof_OpenHRP_mcreekArmControlCartesianService;

OpenHRP::_impl_creekArmControlCartesianService::~_impl_creekArmControlCartesianService() {}


::CORBA::Boolean
OpenHRP::_impl_creekArmControlCartesianService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "setArm") ) {

    _0RL_cd_c027abffb118df27_00000000 _call_desc(_0RL_lcfn_c027abffb118df27_10000000, "setArm", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
OpenHRP::_impl_creekArmControlCartesianService::_ptrToInterface(const char* id)
{
  if( id == ::OpenHRP::creekArmControlCartesianService::_PD_repoId )
    return (::OpenHRP::_impl_creekArmControlCartesianService*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::OpenHRP::creekArmControlCartesianService::_PD_repoId) )
    return (::OpenHRP::_impl_creekArmControlCartesianService*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
OpenHRP::_impl_creekArmControlCartesianService::_mostDerivedRepoId()
{
  return ::OpenHRP::creekArmControlCartesianService::_PD_repoId;
}

POA_OpenHRP::creekArmControlCartesianService::~creekArmControlCartesianService() {}

